// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion: dynamic(() => import("./Accordion")),
  call_to_action: dynamic(() => import("./CallToAction")),
  contact_form: dynamic(() => import("./ContactForm")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  location_cards: dynamic(() => import("./LocationCards")),
  partnerships: dynamic(() => import("./Partnerships")),
  product_showcase: dynamic(() => import("./ProductShowcase")),
  quote: dynamic(() => import("./Quote")),
  review_cards: dynamic(() => import("./ReviewCards")),
  richt_text: dynamic(() => import("./RichtText")),
  services: dynamic(() => import("./ServicesCards")),
  social_cards: dynamic(() => import("./SocialCards")),
  testimonials: dynamic(() => import("./Testimonials")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  trainin: dynamic(() => import("./Trainin")),
  trainin_shop: dynamic(() => import("./TraininShop")),
};
