// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from "./Accordion";
import CallToAction from "./CallToAction";
import ContactForm from "./ContactForm";
import Hero from "./Hero";
import Image from "./Image";
import ImageCards from "./ImageCards";
import LocationCards from "./LocationCards";
import Partnerships from "./Partnerships";
import ProductShowcase from "./ProductShowcase";
import Quote from "./Quote";
import ReviewCards from "./ReviewCards";
import ServicesCards from "./ServicesCards";
import SocialCards from "./SocialCards";
import Testimonials from "./Testimonials";
import Text from "./Text";
import TextWithImage from "./TextWithImage";
import Trainin from "./Trainin";

export {
  Accordion,
  CallToAction,
  ContactForm,
  Hero,
  Image,
  ImageCards,
  LocationCards,
  Partnerships,
  ProductShowcase,
  Quote,
  ReviewCards,
  ServicesCards,
  SocialCards,
  Testimonials,
  Text,
  TextWithImage,
  Trainin,
};

export const components = {
  accordion: Accordion,
  call_to_action: CallToAction,
  contact_form: ContactForm,
  hero: Hero,
  image: Image,
  image_cards: ImageCards,
  location_cards: LocationCards,
  partnerships: Partnerships,
  product_showcase: ProductShowcase,
  quote: Quote,
  review_cards: ReviewCards,
  services: ServicesCards,
  social_cards: SocialCards,
  testimonials: Testimonials,
  text: Text,
  text_with_image: TextWithImage,
  trainin: Trainin,
};
